version: 1.0.0.{build}
configuration: Release
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore source/ChaosMonkey.Guards.sln
- ps: .\version-package.ps1 $env:APPVEYOR_BUILD_VERSION $env:APPVEYOR_REPO_BRANCH
build:
  publish_nuget: true
  verbosity: minimal
nuget:
  account_feed: true
  project_feed: true
artifacts:
- path: source\ChaosMonkey.Guards\bin\release\ChaosMonkey.Guards.dll
- path: source\ChaosMonkey.Guards\bin\release\
  name: ChaosMonkey.Guards.Release
  type: zip
- path: '**\*.nupkg' # find all NuGet packages recursively